trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: adferrand/velero-annotations-controller
  dockerServiceConnection: dockerhub-adferrand

steps:
- task: Docker@2
  displayName: Build and push the Docker image
  inputs:
    containerRegistry: $(dockerServiceConnection)
    repository: $(imageName)
    Dockerfile: src/main/docker/Dockerfile.native
    tags: |
      latest
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
