trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: adferrand/velero-annotations-controller

steps:
- task: Docker@2
  displayName: Build the Docker image
  inputs:
    repository: $(imageName)
    command: build
