{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "velero-annotations-controller.fullname" . }}
  labels:
{{ include "velero-annotations-controller.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - 'list'
  - 'watch'
  - 'get'
  - 'patch'
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - 'list'
  - 'watch'
  - 'get'
  - 'create'
  - 'update'
  - 'patch'
{{- end }}