apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "velero-annotations-controller.fullname" . }}
  labels:
{{ include "velero-annotations-controller.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "velero-annotations-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "velero-annotations-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: VELERO_ANNOTATIONS_CONTROLLER_NS_FILTER
            value: "{{ .Values.namespacesFilter }}"
          - name: VELERO_ANNOTATIONS_CONTROLLER_PVCS_ONLY
            value: "{{ .Values.watchPVCsOnly | quote }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.rbac.create }}
      serviceAccount: {{ include "velero-annotations-controller.fullname" . }}
    {{- end }}