{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "velero-annotations-controller.fullname" . }}
  labels:
{{ include "velero-annotations-controller.labels" . | indent 4 }}
{{- end }}